export const weatherImages = {
  "Partly Cloudy": require("../../assets/images/cloud.png"),
  "Moderate rain": require("../../assets/images/moderaterain.png"),
  "Patchy rain nearby": require("../../assets/images/moderaterain.png"),
  Sunny: require("../../assets/images/sun.png"),
  Clear: require("../../assets/images/sun.png"),
  Overcast: require("../../assets/images/cloud.png"),
  Cloudy: require("../../assets/images/cloud.png"),
  "Light rain": require("../../assets/images/moderaterain.png"),
  "Moderate rain at times": require("../../assets/images/moderaterain.png"),
  "Heavy rain": require("../../assets/images/heavyrain.png"),
  "Heavy rain at times": require("../../assets/images/heavyrain.png"),
  "Moderate or heavy freezing rain": require("../../assets/images/heavyrain.png"),
  "Moderate or heavy rain shower": require("../../assets/images/heavyrain.png"),
  "Moderate or heavy rain with thunder": require("../../assets/images/heavyrain.png"),
  Mist: require("../../assets/images/mist.png"),
  "Light snow": require("../../assets/images/cloud.png"),
  other: require("../../assets/images/moderaterain.png"),
};

export const Colors = {
  black: "#112233",
  white: "white",
  accent: "#333999",
  green: "#60c5a8",
  green2: "#039a83",
  light: "#EEEEEE",
  gray: "#CCCCCC",
  red: "#ff5454",
  gold: "gold",
  purple: "purple",
  skyBlue: "skyblue",
};
